name: Simple Go Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'é€‰æ‹©éƒ¨ç½²çŽ¯å¢ƒ'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'è¦éƒ¨ç½²/å›žæ»šçš„ç‰ˆæœ¬ (commit SHAã€åˆ†æ”¯åæˆ–Tagï¼Œå¦‚: a1b2c3d)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific version
        uses: actions/checkout@v6
        with:
          # ðŸ”„ å›žæ»šæ ¸å¿ƒï¼šæ ¹æ®è¾“å…¥çš„ç‰ˆæœ¬æ£€å‡ºä»£ç 
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          ref: ${{ github.event.inputs.version || 'main' }}
          fetch-depth: 0  # èŽ·å–å®Œæ•´åŽ†å²ï¼Œå¯ä»¥æŒ‰commit SHAæ£€å‡º(è¿™æ ·æŒ‡å®šå¯ä»¥æŒ‰commit id å›žæ»šæ‰ä¸ä¼šæŠ¥é”™)

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Application
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags="-s -w" -o test_git_workflow_app main.go
          echo "æž„å»ºç‰ˆæœ¬: $(git rev-parse --short HEAD)"

      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "test_git_workflow_app"
          target: "/tmp/"

      - name: Deploy with backup
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. å¤‡ä»½å½“å‰ç‰ˆæœ¬ï¼ˆå›žæ»šä¿éšœï¼‰
            BACKUP_DIR="/home/deploy/backups"
            sudo mkdir -p $BACKUP_DIR
            if [ -f "/home/deploy/apps/test_git_workflow_app" ]; then
              BACKUP_NAME="backup_$(date +%Y%m%d_%H%M%S)_$(md5sum /home/deploy/apps/test_git_workflow_app | cut -c1-6)"
              sudo cp /home/deploy/apps/test_git_workflow_app "$BACKUP_DIR/$BACKUP_NAME"
              echo "å·²å¤‡ä»½å½“å‰ç‰ˆæœ¬: $BACKUP_DIR/$BACKUP_NAME"
            fi

            # 2. åœæ­¢æ—§è¿›ç¨‹ï¼ˆä¿ç•™ä½ çš„æ–¹å¼ï¼‰
            pids=$(ps -ef | grep "test_git_workflow_app" | grep -v grep | awk '{print $2}')
            if [ -n "$pids" ]; then
              echo "åœæ­¢æ—§è¿›ç¨‹: $pids"
              kill -9 $pids || true
              sleep 1
            fi

            # 3. éƒ¨ç½²æ–°ç‰ˆæœ¬
            sudo mkdir -p /home/deploy/apps
            sudo mv /tmp/test_git_workflow_app /home/deploy/apps/
            sudo chmod +x /home/deploy/apps/test_git_workflow_app

            # 4. å¯åŠ¨
            cd /home/deploy/apps
            nohup ./test_git_workflow_app > app.log 2>&1 &
            echo $! > app.pid
            echo "å¯åŠ¨æˆåŠŸ PID: $!"

            # 5. è®°å½•éƒ¨ç½²åŽ†å²
            echo "$(date '+%Y-%m-%d %H:%M:%S') | ç‰ˆæœ¬:$(git rev-parse --short HEAD) | çŽ¯å¢ƒ:${{ github.event.inputs.environment }}" >> /home/deploy/deploy_history.log